### ISSUE TITLE
How to use ProjectWBSByProject class?

### ISSUE THREAD

**Issue by roland-d** [picqer/exact-php-client#344]
Hello,

I am trying to load a WBS but it always ends in `Error 400: Bad Request - Error in query syntax.`. Now I have managed to get a couple of other classes to work so I am not completely new but this has me baffled.

The code I have been trying last is:
```
$wbs = new ProjectWBSByProject($this->connection);
$results = $wbs->get(array('projectId' => $project->ID));
```

If I dump the `$wbs` content I get a nice `ProjectWBSByProject Object`. However loading one, fails miserably :)

How would I load a WBS? Thanks for any help.

**Comment by roland-d** [comment]
I don't know if it is the correct way but I have solved it for now using this code:

```
$wbs     = new ProjectWBSByProject($this->connection);
$results = $this->connection->get($wbs->url() . "?projectId=guid'" . $project->ID . "'");
```

**Comment by markjongkind** [comment]
I think you have these options:

**Find by ID**
```
$wbs     = new ProjectWBSByProject($this->connection);
$results = $wbs->find($project->ID);
```

**Filter**
```
$wbs     = new ProjectWBSByProject($this->connection);
$results = $wbs->filter('Project eq guid'" . $project->ID . "'');
```

**Comment by roland-d** [comment]
Hello @markjongkind Thank you for your reply. These options don't seem to work for me. They both give me the error `Error 400: Bad Request - Error in query syntax.`. I am thinking that WBS may not support these options.

**Comment by markjongkind** [comment]
The ProjectWBSByProject entity only supports GET requests to read data, so `find()` and `filter()` should work. It's not possible to create, update or delete ProjectWBSByProject entities.

Can you share a code example?

**Comment by roland-d** [comment]
Sure, I can share a code example. Here is what I have:
```php
$projectGuid = '17489f55-2193-4d0f-9cdd-d3bd3490a21e';
$wbs = new ProjectWBSByProject($this->connection);
$activity = $wbs->find($projectGuid);
```

I hope this is clear enough. Let me know if you need any further information.

**Comment by markjongkind** [comment]
Thanks for your code! Can you try this code, and use a `filter()` instead of `find()`?
```
$projectGuid = '17489f55-2193-4d0f-9cdd-d3bd3490a21e';
$wbs = new ProjectWBSByProject($this->connection);
$results = $wbs->filter('Project eq guid'" . $projectGuid . "'');
$activity = $results[0];
```

_Note: `find()` returns one result and `filter()` returns an array with results_

**Comment by roland-d** [comment]
Hello, I get the same error as before. `Error 400: Bad Request - Error in query syntax. ` This is the code I used:
```php
$projectGuid = '17489f55-2193-4d0f-9cdd-d3bd3490a21e';
$wbs = new ProjectWBSByProject($this->connection);
$results = $wbs->filter("Project eq guid'" . $projectGuid . "'");
$activity = $results[0];
```

Notice I did change the quotes somewhat because in your code example they do not match up.

**Comment by markjongkind** [comment]
> Notice I did change the quotes somewhat because in your code example they do not match up.
They do match up, actually. And I think that is the reason your code is triggering a 'Error in query syntax' error. ;) 

You have to put the $projectGuid value in the GUID query format. The query format is: `Project eq guid'17489f55-2193-4d0f-9cdd-d3bd3490a21e'`. So in your example, this is the correct syntax:

```
$projectGuid = '17489f55-2193-4d0f-9cdd-d3bd3490a21e';
$filter_query = "Project eq guid'" . $projectGuid . "'";
$wbs->filter($filter_query);
```

**Comment by roland-d** [comment]
Now it is getting interesting because with your new code sample, I get the same response of the bad request. So I wonder what is going on here 🤔

**Comment by markjongkind** [comment]
That's weird, it should be working. Are you using the latest version of this library? Have you tested querying other entities? (for example for Projects or Items)

This code is working in production right now:
```
$Item = new \Picqer\Financials\Exact\Item( $connection );
$Items = $Item->filter("ID eq guid'" . $item_guid . "'", '', '');
$my_item = $Items[0];
```

**Comment by roland-d** [comment]
According to my composer.lock I am using the latest version `"version": "v3.18.0",`

Yes, I do query other entities as well. For example:
```
$project            = new Project($this->connection);
$results            = $project->filter("Code eq '" . $event['id'] . "'");
```
```
$transaction = new TimeTransaction($this->connection);
$projectGuid = $projectDetails[0]->ID;

// Check if entry is already booked
$bookedHours = $transaction->filter("Project eq guid'" . $projectGuid . "'");
```

These all work fine. The WBS is the only one throwing a fit :) Although my proposed solution using `$this->connection->get` works as well.

**Comment by markjongkind** [comment]
Maybe there are some weird things going on with the Primary Key and/or API URI of the entity. The [API properties](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadProjectProjectWBSByProject) are showing `ID` as the Primary Key and `Project` as the property to filter by project GUID, but the function URI shows:

> /api/v1/875453/read/project/ProjectWBSByProject?**projectId**={Edm.Guid}

 ... so maybe this endpoint only works when you use the `projectId` property. You could try changing your query from `Project eq guid''` to `projectId eq guid''`, according to your proposed solution, this should work.

```
$projectGuid = '17489f55-2193-4d0f-9cdd-d3bd3490a21e';
$results = $wbs->filter("projectId eq guid'" . $projectGuid . "'");
$activity = $results[0];
```

**Comment by markjongkind** [comment]
The `AccountItem` entity seems to have this issue as well: `accountID` is required based on [the documentation](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadLogisticsAccountItems), but `accountID` is not mentioned as a property in the properties table and thus not a fillable property in this library. Querying these entities via `find()` or `filter()` is not working.

@stephangroen Do you have any input on how this can be fixed in this library?

**Comment by roland-d** [comment]
@markjongkind 
> so I don't think the above code works. 

Correct, I gave it a try but still the same error.

**Comment by justijndepover** [comment]
The documentation for ProjectWBSByProject states that the URI should be
```
/api/v1/{division}/read/project/ProjectWBSByProject?projectId={Edm.Guid}
```

and for a different type of resource: (Item)
```
/api/v1/{division}/logistics/Items?$filter=ID eq guid'00000000-0000-0000-0000-000000000000'
```

So the projectId should be passed as a get parameter.
The plugin provides an easy way to pass parameters to the actual request like so:
```php
$wbs = new ProjectWBSByProject($this->connection);
$result = $wbs->get(['projectId' => 'guid\'17489f55-2193-4d0f-9cdd-d3bd3490a21e\'']);
```
